import './Theme.svelte.css';
/* src/components/globals/Theme.svelte generated by Svelte v3.43.1 */
import { SvelteComponent, init, safe_not_equal } from "../../../_snowpack/pkg/svelte.internal.v3.43.1.js";

class Theme extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, null, null, safe_not_equal, {});
	}
}

export default Theme;