/* src/components/Footer.svelte generated by Svelte v3.43.1 */
import {
	SvelteComponent,
	attr,
	detach,
	element,
	init,
	insert,
	noop,
	safe_not_equal
} from "../../_snowpack/pkg/svelte.internal.v3.43.1.js";

function create_fragment(ctx) {
	let footer;

	return {
		c() {
			footer = element("footer");

			footer.innerHTML = `<div><span class="footer-title">Services</span>  
    <a class="link link-hover">Branding</a>  
    <a class="link link-hover">Design</a>  
    <a class="link link-hover">Marketing</a>  
    <a class="link link-hover">Advertisement</a></div>  
  <div><span class="footer-title">Company</span>  
    <a class="link link-hover">About us</a>  
    <a class="link link-hover">Contact</a>  
    <a class="link link-hover">Jobs</a>  
    <a class="link link-hover">Press kit</a></div>  
  <div><span class="footer-title">Legal</span>  
    <a class="link link-hover">Terms of use</a>  
    <a class="link link-hover">Privacy policy</a>  
    <a class="link link-hover">Cookie policy</a></div>  
  <div><span class="footer-title">Newsletter</span>  
    <div class="form-control w-80"><label class="label"><span class="label-text">Enter your email address</span></label>  
      <div class="relative"><input type="text" placeholder="username@site.com" class="w-full pr-16 input input-bordered"/>  
        <button class="absolute top-0 right-0 rounded-l-none btn btn-primary">Subscribe</button></div></div></div>`;

			attr(footer, "class", "p-10 footer bg-base-200 text-base-content");
		},
		m(target, anchor) {
			insert(target, footer, anchor);
		},
		p: noop,
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(footer);
		}
	};
}

class Footer extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, null, create_fragment, safe_not_equal, {});
	}
}

export default Footer;